# Sonar project analysis properties overrides
# Automatic analysis ignores this file, and uses .sonarcloud.properties instead

sonar.projectKey=LizardByte_libvirtualhid

sonar.exclusions=third-party/**

# sonar.cfamily.reportingCppStandardOverride=c++23
