---
# See https://github.com/LizardByte/beautiful-jekyll-next/blob/master/_config.yml for documented options

avatar: "/assets/img/navbar-avatar.png"
windows_license_purchase_url: "https://buy.polar.sh/polar_cl_zj6Io5NVukXfZSl97ULtFvImfI5L1jbL2cSnc0Y72Pt"
